package Exercise21_7;

public class aReallyLongString {

	public aReallyLongString() {
		
	}
	
	public String getThatString() {
		
		return "NaNoWriMo vs. Tirby\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "By Figaroean Writer\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 1, Halloween and the beginning of NaNoWriMo \r\n"
				+ "\r\n"
				+ "\r\n"
				+ "         What is the point of NaNoWriMo? I doubt that one-fifth of the students will be authors. Well, I know that I will never be an author. Last year I was excused from NaNoWriMo. I swear it was an angel that did that. But now, the angel is not here to do that.\r\n"
				+ "For Halloween, I was a candy bar because you are what you eat! And I eat a lot of candy. I stayed out trick or treating until 9:00 pm. I got so much candy. I was so happy. Then I remembered November. And that means NaNoWriMo. I don't even know what I am going to write about.\r\n"
				+ "I am terrified. I wish I could acrylic freeze myself just for November. And yes, Thanksgiving is worth missing if you also get to miss NaNoWriMo. The first morning of November I woke up shivering with fear. I got dressed and went upstairs for breakfast. When my Mom saw me shivering she asked, \"Is there something wrong Tirby?\"\r\n"
				+ "\"Yes,\" I replied. \"NaNoWriMo is wrong. I don't get why we have to do it.\"\r\n"
				+ "\"Your teachers know what’s best for you. And Braidy is always there to help you.\" Mom explained.\r\n"
				+ "\"What if I fail?\" I asked my Mom. \"The teachers would kill me.\"\r\n"
				+ "\"Well if you don't do it at all your teachers will kill you in a more brutal way than if you just tried and failed. So I would try if I were you.\"\r\n"
				+ "\"You just don't understand it, Mom. NaNoWriMo is going to be the death of me.\"\r\n"
				+ "\"Just come and have some breakfast. Maybe your just hungry.\"\r\n"
				+ "I had my breakfast of some eggs and toast. I was glad I had made my lunch the night before. Because that meant that after breakfast I could play my video games until it was time for school. When I got to school and went to my first period which was P.E. I asked Braidy,\"What are you writing about for NaNoWriMo?\"\r\n"
				+ "\"I'm writing about a society of flying cats on the moon that man later discovers,\" Braidy replies. \"What are you writing about?\"\r\n"
				+ "\"I have no idea,\" I said looking at the ground.\r\n"
				+ "\"I'm sure you'll find something to write about. Even if it's what you ate for breakfast stretched out to 10,000 words.\"\r\n"
				+ "\"Stop talking!\" Mr. Cheese said. \"I'm trying to give instructions.\"\r\n"
				+ "Mr. Cheese was the PE teacher. I couldn't pay attention to Mr. Cheeses’ instructions because I was so scared about the next class. Which was the class that we would be writing NaNoWriMo. But I figured out how we did the sport anyways, sort of. We were playing a type of dodge ball that I hadn't played before. At first, It looked like my team would lose but then everything turned around all of a sudden and my team won!\r\n"
				+ "And then there was the next class. English. Where NaNoWriMo lurked. The greatest monster of all. I was so scared. So scared that Braidy and a few other students had to pick me up and carry me to the next class. When I got to English, Mrs. Pally (the English teacher) announced NaNoWriMo. Then I asked Mrs. Pally, knowing the answer as I said it, \"Is there anything else I can do besides NaNoWriMo? Like maybe write 15 essays? Or give you $20? Okay, how about I...\"\r\n"
				+ "\"No. It is required. There can be no exceptions. But maybe I will let you get away with writing less than the others because of your disability to write.\" After Mrs. Pally taught us how to use NaNoWriMo, we started writing. Braidy had already written 150 words and I had not written one.\r\n"
				+ "Braidy looked at my chrome book screen. She saw no words. \"Do you want help? Braidy offered.\r\n"
				+ "\"I need help,\" I replied. \"What am I going to write about?\"\r\n"
				+ "\"What if you wrote a story about your video games?\" Braidy said. \"I think you could make a great story about your video games.\" I think I forgot to mention I like video games.\r\n"
				+ "\"Yes. Why didn't I think of that?\" I replied. I started writing a story about a player in Minecraft. His house got destroyed by monsters. He had to run and hide in a cave. He made weapons to defend the monsters but he hid in the cave for a while. Unfortunately, I only had 75 words by the end of class. I started eating a big snicker bar. Did I mention I eat candy when I am stressed? Well, I do. Braidy recognizes that I eat candy when I am stressed. The more stressed the more candy.\r\n"
				+ "\"You must be stressed,\" Braidy said. \"You haven't finished a snicker bar that big that quickly in... never.\"\r\n"
				+ "\"I only have 75 words on my novel. And you have 400. At my writing rate, I won’t have 10,000 words until January. And the novels are due on December 1st!\" I replied.\r\n"
				+ "\"Tirby, do not worry, you can catch up in study hall.\"\r\n"
				+ "\"But what if I don't?\"\r\n"
				+ "\"Homework?\"\r\n"
				+ "\"Homework is my greatest fear.\"\r\n"
				+ "\"How can homework be your greatest fear?\"\r\n"
				+ "\"I do not know if you know but, I have never done my homework?\"\r\n"
				+ "\"What? How? If you have never done your homework ever, then, how are you able to pass? You would still be in 5th grade or something. How do your parents let you get away with it?\"\r\n"
				+ "\"I hate to tell you this, and you’re probably going to tell a teacher, and the teacher is probably gonna kill me but, I pay someone else to do it. And when I can not afford it, It becomes a missing assignment.\" After I said that Braidy fainted. I failed to wake her wake up. So then I dragged her to her next class. But then I was late for my next class. And then I realized I had had three tardies that week. And that meant lunch detention.\r\n"
				+ "My next class was math. The only class I ace in. And Braidy is not in my math class. But I wish she was. Because she is one of my few friends. For a while, she was my only friend. When I got to my math class I explained to Mr. Furry, \"I am late because Braidy fainted and I could not wake her up so I had to drag her to her next class.\"\r\n"
				+ "\"What? Why didn't you tell a teacher or something?\" Mr. Furry replied.\r\n"
				+ "\"Well, I told you.\" Then half the class laughed at me. It was embarrassing.\r\n"
				+ "\"Well, I guess I can’t argue with that. But you’re still not excused for being late.\"\r\n"
				+ "Yeah. Mr. Furry usually doesn't accept most excuses for being late. I guess I will be eating lunch in the detention room today. That day we had a test. I was the only one who got 100% on it. Mr. Furry told me that I had lunch detention today.\r\n"
				+ "After math class, I went to the detention room to eat my lunch. I am glad I do not have a school lunch today. It was boring. In fourth period Braidy told me she got 147% on her math test. She did a lot of extra credit. I always wondered how she always had amazing grades. Maybe she is like a goddess of school. Some students might start worshiping her. And maybe because the teachers told them to. I kinda feel like that sometimes there is a cast system at the school. The unsuccessful students at the bottom, the average students above them, the successful students above them, the really successful students above them, and the teachers at the top. You guessed it, I am at the bottom of that cast system.\r\n"
				+ "The rest of the school day went by quickly. Well, not much happened. I got home and turned on the computer to play Minecraft. But as it was powering on, I thought, \"Should I play Minecraft or work on my NaNoWriMo?\" I still have not got fully caught up on my daily average that I am supposed to have. So this time I started working on my NaNoWriMo. I wrote more about this player's journey. The player's name was CREEPER_KILLER_42. He made tools from iron in the cave. He made armor and a sword. That night when the monsters came out he was able to slay monsters and get their loot. He used the loot to his advantage. He used the skeleton bones as a fertilizer in his garden he had just made. He sheered sheep that day to make a bed and be able to skip the night. And then I noticed the word counter. I had written 645 words! That was supposed to be the number of words that I should have on the second day of NaNoWriMo! I was getting ahead.\r\n"
				+ "Then my Mom saw me on NaNoWriMo. \"Your working on NaNoWriMo? And you could have just played Minecraft. Doing your homework is a great thing to do. And you said you hate NaNoWriMo.\" My Mom said\r\n"
				+ "\"Yes, I do hate NaNoWriMo. But I am ahead with it. I already have the amount of words that I should have tomorrow.\" I replied\r\n"
				+ "\"I think you should get a reward for getting ahead even though you didn't have to.\"\r\n"
				+ "\"I was not trying to get ahead. I just looked at my word count and all of a sudden I was ahead. But I will still take the reward.\"\r\n"
				+ "\"OK. I got these new candy bars that are better than every other candy bar. But it is so new, they haven't even advertised it yet. And it’s only for sale at that one shack five miles down that road by the school and into that desert. So do you want one?\"\r\n"
				+ "\"Yes please,\" I replied.\r\n"
				+ "\"I am kinda afraid that if I tell your younger siblings then they will try to steal them.\"\r\n"
				+ "Then my Mom gave me the super good candy bar. When I tried it it was so good. It tasted like chocolate and caramel. And it was really creamy. And it tasted better than ordinary chocolate and caramel.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 2, The Evil Candy Bar\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          After I ate the candy bar I laughed at everything. I started running around and my Dad said, \"Is my son on drugs?\"\r\n"
				+ "\"I swear I am not on drugs,\" I replied as if I couldn’t get a dark dad joke.\r\n"
				+ "\"I think it was the candy bar.\" my Mom said. \"Let’s look at the nutrition facts and ingredients.\" When my Mom looked at the nutrition facts and ingredients we found 30 grams of sugar and 100 milligrams of caffeine. So then we decided to throw the evil candy bars away. But when we looked at the box, it was empty. And then we saw that my younger siblings were eating the candy. \"STOP EATING THOSE!!!\" my Mom yelled. But it was too late. Now my ten-year-old brother James, my eight-year-old sister Lucy, and three-year-old little Susie were gonna be going crazy.\r\n"
				+ "My parents tried to take control of things but it was too chaotic. So we gave up and locked ourselves in my parents’s bedroom and waited for them to calm down. Luckily we were able to play a round of nine card. But not in peace. After the fifth round, we were hungry for dinner. Thankfully the kids had calmed down.\r\n"
				+ "\"I will start making dinner,\" said Mom. \"We will have fruit salad, tater tots, and ground beef. I played Minecraft as I waited for dinner to be ready. Then my Mom told me to set the table. Dinner was fine and after dinner a girl I think nine was years old knocked on our door. My Mom answered it.\r\n"
				+ "\"Hi. Would you...\" the girl said. My Mom saw the same candy bars that made my siblings and I go crazy in a box the girl was carrying. So she slams the door in her face and let out a phew of relief that her children did not go crazy again. I slept OK that night. I was kinda tired in the morning. When I got to school I saw lots of people eating that evil candy bar. The chaos got so bad that in second period, all the kids except for me and Braidy went to detention. When the English teacher went to the bathroom for five minutes, Braidy and I had something that was just as good as a date-ish. We talked about our novels and we even played agar.io on the same server together. Agar.io is a game where you are a circle and you eat to eat bigger. And you can even eat other players.\r\n"
				+ "I got really big and kept accidentally eating Braidy in the game. Then Mrs. Pally came in. She almost saw us on agar.io and not NaNoWriMo. Ok, I am tired of calling it NaNoWriMo so for the rest of the book I will call it NaNo for short. But I can’t believe we didn't get caught on games. But just so you know, I have never seen Braidy play a video game in my life. And she has been my friend for seven years.\r\n"
				+ "But then I realized that half my novel got deleted. And I almost cussed. \"What happened?\" Mrs. Pally asked.\r\n"
				+ "\"HALF MY NOVEL GOT DELETED!!!\" I terrifically replied.\r\n"
				+ "\"How many words did it have?\"\r\n"
				+ "\"1000. It will take forever to catch back up. Or what if I don’t?\"\r\n"
				+ "\"Maybe we get your novel back and maybe we cant. But I won’t punish you just because you couldn't catch up.\"\r\n"
				+ "I had a feeling that this bad luck on NaNoWriMo was going to get worse. So you know what I did to fix it? I just ate a candy bar. But when Mrs. Pally saw it she said, \"Don’t eat that. I don’t want you to go crazy too.\"\r\n"
				+ "\"There’s only a certain type of candy bar that does that. And it’s not this one.\" I replied.\r\n"
				+ "\"I hope so.\"\r\n"
				+ "\"Tirby, I will help you catch up on your novel,\" Braidy said. \"And I think I might even be able to bring that half back.\"\r\n"
				+ "\"Don’t worry about it Braidy. I will do that,\" said Mrs. Pally. But then Braidy sent me a copy of the half that was deleted.\r\n"
				+ "\"Wait, how did you get that copy?\" I asked Braidy.\r\n"
				+ "\"I don’t know if you know but it’s possible to access all the novels in our class. And I made a copy of yours.\" Braidy replied.\r\n"
				+ "\"Why did you make a copy of my novel?\"\r\n"
				+ "\"It’s because I once got bored so I decided to read someone’s novel and I thought that you would have a good one so far. And I copy the new parts of it every day.\" At that moment I wanted to hide in a titanium box. People can read my novel? I will get so embarrassed. I wanted to delete my novel so no one could read it.\r\n"
				+ "So I said, \"Braidy, you can copy my novel and read it but don’t tell anyone about my novel. And don’t tell anyone that they can access the novels.\"\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 3, Baaaaaaaaaaad Luck on NaNo\r\n"
				+ "\r\n"
				+ "          The next day in English I discovered that my chrome book wouldn't boot. It wasn't dead. I just couldn't get it on. So I tried another chrome book. And then a teacher I didn't know came in the classroom. and he asked my English teacher, \"Can I borrow Tirby for a minute?\" Please say no. I thought.\r\n"
				+ "\"Is it important?\" Mrs. Pally asked.\r\n"
				+ "\"Yes. And it can only happen right now.\"\r\n"
				+ "Oh no. I thought in my head. I was behind on NaNo. Even though Braidy saved the deleted half. When the weird guy took me through the hall, I hoped it was all a dream. But it probably wasn't. He took me to this room with no windows. The walls were made of bricks painted black.\r\n"
				+ "\"Have a seat.\" the weird teacher said. This was terrifying. I took a seat at the white table. He took the other seat.\r\n"
				+ "\"Are you the new vice-principal or something?\" I asked. \"Am I in trouble? I didn't do anything wrong. Did I?\"\r\n"
				+ "\"I took you here to have a word with you. And it had to be private.\" I was so scared. I was terrified. Then I heard a voice. It was saying my name.\r\n"
				+ "\"Tirby?Tirby...TIRBY!\" The voice said. And then I woke up to Braidy trying to wake me up. Thank heaven it was just a dream.\r\n"
				+ "\"Did I fall asleep in class again?\" I said.\r\n"
				+ "\"What do you mean again? You have literally never fallen asleep in class before.\" Braidy responded.\r\n"
				+ "\"I think my novel is getting too boring. But I had a dream where this weird teacher took me to a room and talked to me.\" And then my dream came true a few minutes later. It was exactly the same. But when I got into the room, I hoped it was just another dream.\r\n"
				+ "\"Me and my gang dont want you to write your NaNoWriMo novel.\" The weird teacher said.\r\n"
				+ "\"Why don’t you want me to write my novel?\"\r\n"
				+ "\"Tell that to my boss. I’m just trying to stop you so that I get my paycheck.\"\r\n"
				+ "\"So, you make a living off of stopping kids like me from writing NaNoWriMo novels.\"\r\n"
				+ "\"Not exactly. I just do what my boss tells me to do.\"\r\n"
				+ "\"Who is your boss?\"\r\n"
				+ "\"No one knows. He just sends us texts of what to do and he pays us with the apple pay thingy. But we’re getting off-topic. Time for it.\"\r\n"
				+ "\"Time for what?\" And then, out of nowhere, this other guy came into the room and the two guys picked me up and started taking me somewhere.\r\n"
				+ "\"HELP!!!\" I tried to yell. But one of the guys cut me off. I was kicking and fighting but it wasn’t effective. I was so curious about where they were taking me. After a few minutes I was tied up and in a car with my mouth duct-taped shut. The car ride lasted about 20 minutes. But I didn’t know for sure because I couldn’t look at my watch.\r\n"
				+ "When I got to the place they carried me out of the car and into a modern-looking house. When I got inside the walls of the house were painted a blood-red color with black baseboards. How creative and TERRIFYING!!! The two guys took me into a room with no windows and a desk and chairs. They untied me up and ripped the duck tape off my mouth.\r\n"
				+ "\"HELP!!!\" I yelled. But the two guys walked out of the room and locked me in. I assumed no one heard me. Then a guy came into the room but through a different door than how I came in. He wore that one NaNo Viking helmet that is on the head of the website.\r\n"
				+ "\"Hello Tirby.\" the man said.\r\n"
				+ "\"How do you know my name? Why am I here? Is this legal? Are you the boss of those guys?\" I asked.\r\n"
				+ "\"Stop your rambling. You are here with some other kids struggling with NaNoWriMo. I am the creator of NaNoWriMo.\"\r\n"
				+ "\"What? Then why do you want me to not write a NaNoWriMo novel?\"\r\n"
				+ "\"Every time someone like you writes on NaNoWriMo their novel sucks.\"\r\n"
				+ "\"Why do you care if it sucks? How do you know that it sucks?\r\n"
				+ "\"Because I have to read them.\"\r\n"
				+ "\"Can’t you just not read them?\"\r\n"
				+ "\"My Mom makes me. My Mom makes me read every last one of them.\"\r\n"
				+ "\"How would you ever get the time to read all those novels? That would be thousands. Hundreds of thousands. Maybe even millions.\"\r\n"
				+ "\"That’s why NaNoWriMo is only once a year. I do like to read the novels though. I made NaNoWriMo so I could read novels. But also because my Mom told me I needed to read more. And then someone just had to put NaNoWriMo on the news.\"\r\n"
				+ "\"If you like to read novels then why do you not want to read mine?\"\r\n"
				+ "\"We are getting off-topic. You are here to delete your novel, your NaNoWriMo account, and for me to take all your memories of NaNoWriMo.\"\r\n"
				+ "\"What? But I will get in trouble if I don’t do NaNoWriMo. And how can you take my memories?\" Then the guy pulled out a chrome book.\r\n"
				+ "\"Tell me your email and your password. Or else.\"\r\n"
				+ "\"I am not gonna tell you if your gonna delete my NaNoWriMo novel and account.\"\r\n"
				+ "\"The or else is about to happen. There are worse things than sitting in a room with a creepy guy.\"\r\n"
				+ "\"Child abuse is illegal. I will call the police.\"\r\n"
				+ "\"But how can you call the police without a phone?\" And then I remembered. I have a cell phone in my pocket. I thought that if I knew his name then the police could find out where he lives. Or maybe I can google the name of the creator of NaNo. It would use data but, so what? I gotta get outta here.\r\n"
				+ "\"Tell me your chrome book stuff now.\" the guy said.\r\n"
				+ "\"No\" I replied.\r\n"
				+ "\"Don’t make me.\" And then I remembered. If you ask Sirri where you are she tells you the address. And then I thought of the perfect plan.\r\n"
				+ "\"Ok fine. I will tell you my chrome book login stuff. But first, may I go to the bathroom? I really have to go.\"\r\n"
				+ "\"Tell me your chrome book stuff first.\"\r\n"
				+ "\"If you don’t let me go know, you might have to clean up pee.\"\r\n"
				+ "\"I can make you do it.\"\r\n"
				+ "\"But I don’t know-how. And by the time you would have taught me, the stain would take a while to clean up. And you want to take my memories now.\"\r\n"
				+ "\"Fine. The bathroom is through this door, down the left hall, second door.\" When I got to the bathroom, I asked Siri where I was, and then I called the police.\r\n"
				+ "When the police called the other end said, \"Tomato City 911. What is your emergency?\"\r\n"
				+ "\"I need the police! I have been kidnapped!\" I responded.\r\n"
				+ "\"Ok. Where are you, young man?\"\r\n"
				+ "\"I am at 1520 north, 6342 west, Tomato City UT.\"\r\n"
				+ "\"What is your name?\"\r\n"
				+ "\"TIrby Yensen.\"\r\n"
				+ "\"We will be there right away. You can hang up now.\" Then I flushed the toilet and washed my hands to make it sound like I was actually going to the bathroom.\r\n"
				+ "When I got back to the room with the creepy guy, he said, \"Now tell me your email and password. And you do want the or else to happen.\" I tried to come up with another excuse not to. An excuse that would take up the minute that the police need to use to get here.\r\n"
				+ "\"My email is kirbyjensen@gpacharter.org.\"\r\n"
				+ "\"And what is your password?\"\r\n"
				+ "\"Oldwalrus43.\"\r\n"
				+ "\"It didnt work! Tell me the truth!\"\r\n"
				+ "\"I think you messed up. Let me try.\" And then, I pretended typing in oldwalrus43. And I purposely made a mistake. Then the police were here. They broke into the house.\r\n"
				+ "\"Tirby Yensen?\" A voice said.\r\n"
				+ "\"He could his mouth taped right now.\" Another voice said. Finally they busted down the door of the room I was in.\r\n"
				+ "\"Is that you Tirby Yensen?\" the cop said.\r\n"
				+ "\"Yes! I need help.\" I responded. And then the weird guy (not the cop) picked me up and started running. I tried to escape him but I could not. But fortunately the cop was able to capture the weird guy and set me free.\r\n"
				+ "\"I am taking you to court.\" the cop said to the weird guy. \"And Tirby, you have to come to because you’re the victim.\"\r\n"
				+ "\"Shouldn’t my parents know about this?\" I asked.\r\n"
				+ "\"Yes. In fact, I think your parents should also come to the court.\" the cop replied. So I called my parents and everyone came to court.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 4, Hey! Go to court!\r\n"
				+ "\r\n"
				+ "When we got to court, I was kind of scared. \"Take a seat everyone.\" the judge said. So we all took a seat. Even my English teacher was there.\r\n"
				+ "\"What happened to you?\" my Mom asked me.\r\n"
				+ "\"I, I was kidnapped in the middle of school and taken to the house of the creator of NaNoWriMo I think.\"\r\n"
				+ "\"Whose fault was it that you got kidnapped?\" my Dad said with anger towards the kidnappers.\r\n"
				+ "\"It was this weird teacher I don’t know the name of.\"\r\n"
				+ "\"You are going to skip school until this problem is figured out and solved.\" my Mom said.\r\n"
				+ "\"Hey. I decide that stuff.\" the judge said. \"Let us begin the trial. Dan Tatertot, you have been accused of kidnapping Tirby Yensen.\" I never knew the creator of NaNoWriMo was named Dan Tatertot. It makes me hungry. I looked at my watch and I noticed that if I were at school I would be eating lunch. Too bad you can’t eat in court.\r\n"
				+ "\"Me? I never touched Tirby. It was all Jack Engler and his helper Dody Walker.\" then the jury stared at Dan Tatertot.\r\n"
				+ "\"You are half lying.\" the jury said. \"You were part of the kidnapping of Tirby Yensen, and yes, Jack Engler and Dody Walker were a part of it.\"\r\n"
				+ "\"Tirby Yensen, you told the cops you were kidnaped. Is this true?\" the judge asked.\r\n"
				+ "\"Yes. Well, it was actually these two guys that I don’t know the name of but I think that Dan Tatertot is their boss. I think he pays them with the apple pay thingy. Do you know about it? I think it came in iOS 12...\" I said. But then the judge cut me off saying:\r\n"
				+ "\"Ok, Ok, Ok. That enough talking and we need to stay on topic. Jury, is he lying?\"\r\n"
				+ "\"No.\" the jury said. Juries are amazing at sensing if you are lying or telling the truth.\r\n"
				+ "\"Judge.\" my English teacher said.\r\n"
				+ "\"Yes.\" the judge said.\r\n"
				+ "\"I just had something to add. A man came to me saying he needed to borrow Tirby Yensen for a minute. I thought he was the new teacher at the school but Tirby Yensen didnt come back. I think that teacher was one of the kidnappers.\"\r\n"
				+ "\"She is telling the truth.\" the jury said.\"\r\n"
				+ "\"Is there anyone who defending Dan Tatertot?\" the judge asked.\r\n"
				+ "\"Im defending Dan Tatertot.\" Dan Tatertot said.\r\n"
				+ "\"You are Dan Tatertot.\" the judge replied. I was starving. And I wanted this to end quickly.\r\n"
				+ "\"Who says I can’t defend myself?\"\r\n"
				+ "\"Stop acting like a child.\" then, those two people who kidnapped me came into the room. \"Who are you two and why are you here?\" the judge said.\r\n"
				+ "\"Two cops made us come here.\" one of the guys said.\r\n"
				+ "\"I still don’t know who are you.\" the judge said.\r\n"
				+ "\"I am Jack Engler.\" one of them said.\r\n"
				+ "\"And I am Dody Walker.\" the other said.\r\n"
				+ "\"They are the kidnappers.\" Dan Tatertot said.\r\n"
				+ "\"But they brought me to Dan Tatertot and he tried to destroy my NaNoWriMo which is part of my schooling. So Dan Tatertot is also guilty.\" I said.\r\n"
				+ "\"He is telling the truth.\" the jury said.\r\n"
				+ "\"Wait. Your the one who texts us assignments and pays us with apple pay, Dan Tatertot?\"\r\n"
				+ "\"You figured it out. I am your secret boss.\"\r\n"
				+ "\"According to all this evidence, Dan Tatertot is guilty, Jack Engler is also guilty, Dody Wakker is guilty as well. Tirby Yensen is Innocent, and Cattie Pally is innocent.\" the jury said.\r\n"
				+ "\"Dan Tatertot, for lying in court your punishment will be heavier than if you just told the truth. Dan Tatertot, 20 years of jail for rewarding criminals, and one extra year of jail for lying in court. Dody Walker and Jack Engler, you both get ten years of jail for kidnapping Tirby Yensen.\" the judge said. \"Case closed.\" then a few cops came out and cuffed the criminals and took them away. Then my parents took me back to school and I ate my lunch. The rest of the day went smoothly.  But I was still kind of afraid of getting kidnapped. So the next day I tried to get out of going to school.\r\n"
				+ "I pretended to be sick but then my parents found that out. \"Why were you pretending to be sick?\" my Mom asked.\r\n"
				+ "\"I’m just afraid of getting kidnapped again,\" I said. \"Dan Tatertot must have more than just two henchmen working for him. He could have 100 people trying to get me.\"\r\n"
				+ "\"But why would they do it if they’re not getting paid. Dan Tatertot cant pay em if he’s in jail.\" so then I had no excuse for not going to school. I wish I did. I was still afraid. Maybe they didnt see Dan Tatertot’s phone and maybe his workers are still out there doing bad stuff. I was scared to be at school that day. Same with the next day. I don’t know what I am gonna do about this.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ " Chapter 5, NaNotv AKA my nightmare\r\n"
				+ "\r\n"
				+ "Three days have passed from the day I got kidnapped. Still kind of scared. So I am slightly more cautious and alert. What I am really scared of is NaNotv. It’s where we have to be interviewed as if we were our main character. When we were supposed to sign our name on the board for volunteering, the only person who wrote their name was Braidy. I could see her doing it though.\r\n"
				+ "\"No one else is volunteering for being interviewed? You know what that means, the stick bucket. I will draw your names out. The bucket will volunteer you then.\" Mrs. Pally said. \"Well Braidy, It looks like you go first.\" so Braidy got up and sat in the red chair.\r\n"
				+ "\"Hello. I am a cat with wings. My name is Jessie.\" Braidy said. Mrs. Pally was the hostess.\r\n"
				+ "\"Tell me about your hometown.\" Mrs. Pally said.\r\n"
				+ "\"I don’t really have a hometown because my society lives on the moon.\"\r\n"
				+ "\"May I ask why man have not seen you?\"\r\n"
				+ "\"Yes. It’s because we are good at hiding.\"\r\n"
				+ "\"What is it like on the moon?\"\r\n"
				+ "\"Well, we kinda live underground. We eat stuff that we can grow on the moon. We don’t really go to school but our parents teach us how to do things. And after I finish my chores I play with my friends.\"\r\n"
				+ "\"Do you have a greatest fear you would like to share with us?\"\r\n"
				+ "\"Yes. I fear that man will find us and do something bad to us.\"\r\n"
				+ "\"What is your goal in life?\"\r\n"
				+ "\"To not die and to keep man from finding us.\"\r\n"
				+ "\"Any questions from the audience?\" and there were no questions from the audience. A few other people went and then no one else had their name on the board. So Mrs. Pally drew sticks.\r\n"
				+ "\"Please not me. Please not me.\" I told to myself.\r\n"
				+ "\"Tirby Yensen.\" Mrs. Pally said. Oh crap. I am going to die. And because I was so afraid I ran out of the classroom. I could tell my adrenaline had released. Was NaNo tv really that scary? Well I guess it is. I wish there was an angel that could save me from this. I ran home and locked myself in my room.\r\n"
				+ "\"What the #@$% happened Tirby?\" my Mom shouted.\r\n"
				+ "\"The school is on fire!\" I lied. I shouldn’t have said that but NaNo tv is no excuse for running out of the school.\r\n"
				+ "\"Then why didnt the school call me?\" my Mom asked.\r\n"
				+ "\"Oh. Bad news. The school telephone wire broke.\" I lied again. Then I saw the police come. There were like six police cars. And oh no. They were at my house. But they didn't look like regular police cars. They looked strange. So then I told my Mom. \"Oh no. Mom, we gotta get in the car, pick up the rest of the family as fast as we can, and then head to...somewhere other than here. And for some crazy reason, we did that. We started speeding at 150 miles per hour. And like the whole freeway was flooded with police cars chasing us. There were even helicopters.\r\n"
				+ "I was hoping that they would not catch us but they did. They took me to a portal and I managed to break loose from them. I started running. And then I was going as fast as the car I was just riding in. Then faster. But then I tripped over a rock and started flying. Then I was flying back towards the people who were trying to catch me. Then they got me again and shoved me through the portal. I was the only one on the other side. Until I died. I hit a rock way too hard. It was a pretty big rock. I wondered who was going to finish this novel while I was gone. When I found out I was in a novel.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 6, The New Novel Taker\r\n"
				+ "\r\n"
				+ "The person writing this right now is not Tirby Yensen. The rest of the book will be written by me. Braidy. You know me. But what happened was this weird person that was wearing the NaNoWriMo helmet told me that Tirby had died and that we are in a novel. He told me that Tirby was the main character and that now I should be. But I refused after the first paragraph.\r\n"
				+ "This is no longer Braidy who is writing. This is that weird person Braidy was talking about. If I couldn't get Braidy to be the new main character then I guess I must be. Because Braidy refused we did the same thing to her that those guys did to Tirby a minute ago. But then someone captured me so I had to throw the main character ownership to Mrs. Pally. I was taken to jail and Mrs. Pally was killed. And then I died.\r\n"
				+ "Hello. I just found this thing on the ground. And I think it makes me the main character in a novel. People have been disappearing and I think I will also disappear. I hope I don’t but I might. My name is Pate. I have been having some trouble on NaNoWriMo and it looks like someone is about to capture me. Oh no. Now I’m captured and the people that have captured me are flying. Really high up. And I’m flying with them. I think they might drop me. And they just did. But luckily there was a big mattress to break my fall. Wait. Where did the mattress come from? And now the cops are here and they captured me. And now I’m in a police car. Now I’m in a jail cell. And my cellmate killed me. And then my cellmate died. And then the cops died. And then everyone in the jail died.\r\n"
				+ "Oh hello. I am a magical being that found this crystal that makes me the main character in a novel. I have noticed that a lot of people in this novel have been dying. But I think because of my magical abilities I will not die. My name is Bobby. I am male. I am known as the space Unicron because I deliver rainbows. Well, I did deliver rainbows but then I got too old. And I don’t want to do this. So I am giving this crystal to someone else. But who. The crystal is stuck to me with a magnetic force. And just so you know, all of this craziness is not Tirbys dream. But I kind of feel bad for him because he died. But I think I can revive him.\r\n"
				+ "So I will make a portal that goes to where he is. And then look for him. So I am now making a portal and now it’s ready. So I went through it and I found Tirbys dead body. And I think I know a spell that can revive him. Oh. I think I should tell you that I am a unicorn. And what do I know? The reviving spell worked! Tirby is alive.\r\n"
				+ "\"Who are you!!??\" Tirby yelled. \"Are you going to kill me? Wait. How I am I alive again?\"\r\n"
				+ "\"I am known as the space unicorn. And yes, I am a unicorn and I revived you.\" I replied.\r\n"
				+ "\"Am I still the main character?\"\r\n"
				+ "\"I don’t know. This weird crystal came to me. And this crystal makes me the main character. But I will try throwing it at you.\" So then I threw the crystal to Tirby. And it came right back to me like I was a magnet and the crystal was a paper clip.\r\n"
				+ "\"I think you might die,\" Tirby told me. \"I died. And I was the main character from the start. And a lot of people in this novel are dying.\" Then these weird guys captured Tirby, took him through the portal that led back to the normal world. So I followed. But then they threw him through the portal that takes you to the other place that I was just in and Tirby hit that big rock again. He died. So I ran to revive him.\r\n"
				+ "But then I heard a voice say,\"Don’t, even, think about it.\"\r\n"
				+ "\"Reviving Tirby?\" I asked.\r\n"
				+ "\"Yes.\" the voice said. \"In this novel, he was meant to be dead.\"\r\n"
				+ "\"What about Braidy?\"\r\n"
				+ "\"How do you know about Braidy.\"\r\n"
				+ "\"I don’t know. I just kinda found out with this crystal. It like tells me everything about this novel we are in. But I am reviving Tirby and you can’t stop me.\" So I tried to revive Tirby but then I was lifted up into the air by this weird force. I was going up pretty high. I’m a unicorn, not an alicorn so I don’t have wings. Then I started falling back down. I was coming down really fast. And then I hit the ground and got knocked out.\r\n"
				+ "I woke up in a room chained to what looked like a surgery table. You know. Those things they put patients on when they have to give them surgery. There were some people surrounding me. I tried to use my magic to break free but my magic didnt work!\r\n"
				+ "\"I knew it was a good idea to paralyze your horn.\" one of the people said.\r\n"
				+ "\"You really are the best at making ideas.\" another person said.\r\n"
				+ "\"I hate to do this to you. But because you just can’t handle having that magic, I must cut off your horn.\" the first person said to me. So then he pulled out a saw. Like one of those saws they use to cut down trees. And he started cutting my horn off. It hurt. A lot. My horn was paralyzed not numbed. \"This horn is tough. Will you grab the other end and help me?\"\r\n"
				+ "\"Sure.\" the other person said.\r\n"
				+ "\"Why are you cutting off my horn!!??\" I yelled.\r\n"
				+ "\"Didnt I just barely explain that?\" the first person said. Then everyone else started laughing.\r\n"
				+ "\"I need my horn!!\" I said.\r\n"
				+ "\"No, you don’t. You only need it to revive Tirby. And we don’t want that. And I can control pretty much anything in this world.\" the first person said again.\r\n"
				+ "\"Then why didnt you just make my horn disappear!!??\"\r\n"
				+ "\"Because it wouldn’t have been as much fun for us. Wouldnt it? Bob, duck tape his mouth. I’m tired of his talking.\" So then my mouth was taped shut. \"You know what. How about we make him permanently mute. The novel might be a bit more interesting that way.\" My horn was almost cut off. But wait. These chains are getting kind of loose. Maybe I can break free. \"Someone tighten the chains. They are getting loose.\" Ah man. I almost escaped. And then my horn was fully cut off. \"OK well,l let’s see, am I feeling generous? Well, I kinda feel bad that I am torturing this unicorn so how about I make it so it was as if he wasn’t supposed to have a horn. Then it won’t hurt as much.\" and then it happened.\r\n"
				+ "\"And now we are done with the unicorn. Bob, you can now set the unicorn free.\" the other person said. So then the chains were loosened and \"the Bob\" ripped the duck tape off my mouth.\r\n"
				+ "\"Wait! There is one more thing I must do to the unicorn! Remember how I said I was going to mute him?\" the first person said.\r\n"
				+ "\"Call me Space Unicorn and please oh please I beg you I need my voice. You know I do so please don’t...\" I said. I would have finished with \"mute me\" at that last part but it was too late. I could not speak. Not a sound. Well, no one will ever tell me to be quiet. Then a portal appeared. I looked into it and it was the portal to where I just was in the normal world. I do not know what I am going to do without my magic and my voice. Life will be a lot duller.\r\n"
				+ "I went back to Tirby's old school. (Well it was his school until he died.) I thought I might as well get captured by animal control and be taken to a lab. I don’t have much else to do with my life. And then I remembered my family. I gotta run away before they notice me. Wait. I cant get back to the land of the unicorns without my magic. I guess there is really nothing to my life. Well, I guess I will try to die in my misery. Or will I? Yep, I am suiciding.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 7, I’m Invincible?\r\n"
				+ "\r\n"
				+ "I tried to kill myself. First I try banging my head against a rock as hard as I could. I think I did it for like an hour. I wasn’t even hurt. And then I tried diving to the deepest part of a lake. Maybe drown myself. Then a portal opened. A ghost came out of it. It was the ghost of Tirby! \"Hello.\" his ghost said. \"I am now like a guardian angel of the characters in this novel. I tell them stuff about the novel. I know you cant talk. I found this paper and pen if you want to communicate with me.\" then I started writing on the paper. I asked him if he could help me get to the land of the unicorns. I also asked him why I am not dead. Oh just so you know, I went out of the water.\r\n"
				+ "\"I can and will help you get to the land of the unicorns,\" Tirby said. \"And the reason why you are not dead is because death was forbidden. But only for a weak. I have some power. And I think I might be able to make a portal for you that takes you to the land of the unicorns.\" then a person appeared. And it was the same person that cut my horn off! I charged at him.\r\n"
				+ "\"I don’t think that’s a good idea.\" the person said somehow flying up and out of the way. \"And Tirby, don’t lie to Space Unicorn. Death isn’t forbidden it’s just that Space Unicorn is forgetting that he is harder to kill than most other creatures.\"\r\n"
				+ "\"OK. I will stop lying to Space Unicorn. And, I am requesting the power to make portals.\" Tirby said.\r\n"
				+ "\"And why do you want this power? You can always use the portal staff.\"\r\n"
				+ "\"But the portals only go to this world and the novel creator market. I want to be able to send the Space Unicorn back to the unicorn land.\"\r\n"
				+ "\"If you can kill Space Unicorn without him feeling any pain then Space Unicorn will be revived and will wake up in the unicorn land. And if you can do that then there is a 55% chance that he will get his horn back. But you also have to give me $100 of your novel bucks. And you will also have extra chores for a month. Deal?\"\r\n"
				+ "\"Deal!\"\r\n"
				+ "I might have something to give you in return. I wrote on that paper. Then that guy disappeared. \"We gotta find out a way to kill you without any pain. Oh! I know! What if I put you into a comma, fly you up 90,000 feet above an erupting volcano, and then drop you into it! Do you think it will work? Or I could try to make you laugh so hard you pass out and then I duck tape your mouth and nose?\" Then I had an idea. So I wrote it on the paper. It was, I think if you cut my head off fast enough then my spinal cord will be cut before I feel the pain! And just to be sure you could num my entire body.\r\n"
				+ "\"Well OK. your idea is great. And I think we could get the stuff at the novel creator market. And that place is the only place I can make a portal to. So let’s go!\" Tirby said. So then, we went to the novel creator market. I had never heard of this place. Well, until now. It looked like a place where the creators of this novel chill and make novels. \"I have more power here than I do in the novel world,\" Tirby said. But I think I should hide you because there aren’t very many people here and I might get in trouble if someone finds out that I took you here from the novel world.\" so then I was turned invisible.\r\n"
				+ "\"Hey Tirby.\" a beautiful girl said. It may have been Brady.\r\n"
				+ "\"Hey, Braidy,\" Tirby said back. \"What are you up to?\"\r\n"
				+ "\"Oh not much. I was just gonna go get something to eat.\"\r\n"
				+ "\"But ghosts don’t eat.\"\r\n"
				+ "\"I can if I want to. I just eat it for the taste.\"\r\n"
				+ "\"Well I got stuff I need to do and I’m kind of in a hurry so bye.\"\r\n"
				+ "\"Bye.\"\r\n"
				+ "Then I wrote on the paper, are you sure this plan is going to work? Im a unicorn so killing me is going to be hard.\r\n"
				+ "\"Well, then we must get a titanium ax. But I don’t know if I can afford it.\" Tirby said.\r\n"
				+ "And then I wrote, if you can’t afford it then will you have to steal it?\r\n"
				+ "\"I am afraid so. Well, first let’s see if I can afford it.\" so we went to a weapon store and we found the titanium ax. Triby tried to buy it but the accountant said that Tirby did not have enough money. So then Tirby stole it. And he ran. But then this metal ball came at him really fast. When you are a ghost the only part of your body that you have is your bones. So Tirbys bones shattered. He still had his spirit but he could not pick up the ax.\r\n"
				+ "And who threw that metal ball? Oh, just the same person who cut off my horn! From now on in the book, I am calling that guy Mr. Evil.\r\n"
				+ "\"Well hello, Tirby.\" Mr. Evil said.\r\n"
				+ "\"Why do you keep throwing those titanium balls at me? TIrby replied. \"And why come the titanium ball only works on my bones? I’ve seen it. Whenever that ball hits anyone else it’s as if the ball didnt touch them.\"\r\n"
				+ "\"Oh, that’s just because I smote you with that curse. The reason why is because I hate you.\"\r\n"
				+ "\"Why do you hate me?\"\r\n"
				+ "\"Why do you think?\"\r\n"
				+ "\"I've gotta go. There are things I gotta do.\"\r\n"
				+ "\"I think the only place you'll be going is to jail. You just stole something.\" By now the cops were here. Or so I think they were cops. Fortunately, by then, Tirby's bone pieces were back together. So he picked up the ax and ran. Really fast. I could barely catch up. Then we got to what looked like a portal staff. He made a portal but right before he could step in, a cop grabbed him. And then a force picked him up and threw him out of my sight.\r\n"
				+ "And then somehow without me knowing it, my invisibility disappeared. But for some reason, they didn't take me. One of them just said, \"Well now we know that Tirby Yensen is guilty of thievery, and hiding illegal immigrants! We must take a picture to get the evidence.\" I tried to run away but it was too late. They already had the evidence and now Tirby was in trouble. So this time I didn't run through the portal. I ran away from that mob of cops. \"Stop right there!\" one of the cops yelled. They were probably going to send me back to the world of the novel.\r\n"
				+ "But then a force picked me up and threw me through the portal. I hit a rock hard enough to pass out. I woke up in a cave. A cave with bears in it. One of them had taken a bite of me. But then a portal appeared right below me. I fell in it. I landed on a metal spike in unicorn land. I died. But I woke up revived and in my house in Unicorn land. I saw the crystal that makes you the main character fly away. But I still had just enough time to read the note that had appeared. It said, I just thought that Tirby Yensen won't be able to take you back to the land of the unicorns. So I did. You are still mute but you may or may not have your horn back. Tirby is probably going to be destroyed. But that won't matter to you because every memory you have of this week will be erased when you finish reading this letter. Who's Tirby? Oops.\r\n"
				+ "I finished that letter on accident. But now I don't know who Tirby is and I don't know why my horn is gone or why no matter how hard I try I can't make a vocal sound. And I can see a crystal flying away from me.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Chapter 8, Tirby's Life in Jail...Jailbreak?\r\n"
				+ "\r\n"
				+ "This is Tirby again. I am in jail right now. I don't know if I will ever get out. Then I see the leader of this world, the world of the novel, and the person who likes to throw titanium balls at me. In these worlds, he pretty much has infinite power. He comes to my jail cell. \"Hey, Tirby. I brought you something,\" he said. \"It’s just a little something that you had in the novel world. Remember NaNoWriMo?\" I was terrified.\r\n"
				+ "\"Please no. I will do anything else besides NaNoWriMo! Anything!\" I replied.\r\n"
				+ "\"Anything?\" now I was really terrified. Why did I say that? If only I had never stolen that ax. \"You don't wanna have to call yourself a liar. Do you?\" who knows what would happen to me.\r\n"
				+ "For some crazy reason, I figured it was best to say, \"I lied about that. I guess I have to call myself a liar.\" but after I said this, I regretted it so bad I could have killed myself in that moment. Because he might make it so that no one would ever trust me.\r\n"
				+ "But I regretted it less when he said, \"Well, people say what you just said all the time. It must have been an accident. But you will be doing NaNoWriMo until the day your book hits 100,000 words.\"\r\n"
				+ "\"Well, even though I wouldn't do just anything over that, I would do a lot of things. Like I would rather be your slave for a year.\"\r\n"
				+ "\"There is something I should tell you. did you know that I am the one who writes this novel you are in? I really do control everything. And I use you in this novel. So technically, you already are my slave. And you don't even notice it. It feels like your the one who makes your decisions.\" it took me a while to process all of this.\r\n"
				+ "But when I finally was able to figure out what he had just told me, I got back at him saying, \"Well then you’re just cruel! If you are just going to make characters and then kill them. And you enslave them. And you abuse them. And you think its all OK just because I am in a novel?\" and then it hit me. If he really controlled everything here then he is calling himself cruel. If we are in a novel then we don't exist. We're just that leader or creator talking to himself. I tried not to let this thought make me depressed.\r\n"
				+ "I think that running out of the classroom when it was my turn to do NaNo tv was the dumbest thing I ever did. But then I process that it was the dumbest thing he ever made me do. He's right. It does feel like I can make my own decisions.\r\n"
				+ "\"Tirby.\" the leader said. \"There is something I should tell you. I have to do NaNoWriMo too.\" I didn't know anything about the real world. The world that made the person that made this novel. But now I know that in the real world, there in NaNoWriMo. And then I remembered. In my NaNo novel, I was also planning to kill my main character. Why did the leader do this to me? I think I forgot to mention that no one knows the real name of the leader. Or at least, no one in these worlds. But then I realized, if the land of this novel is the world I was born in, and this experience I'm having is also in the novel, then it's just one realm with two worlds. \"But Tirby, you should get started on your novel.\" the leader said. \"But I will make you a deal. I will let you go back to the world of the novel as a person with a body, and if you can successfully finish your NaNoWriMo novel and do an interview on NaNo tv, then I will let you live with your family and friends in peace. And you won't see this world again till 88 years. But 100,000 words NaNoWriMo will still be here waiting for you. But I will make it so you can do NaNo tv right now. Just walk through that door. Deal?\"\r\n"
				+ "\"Can I have time to weigh the pros and cons?\" I said. \"I don't know because now I know that I'm in NaNoWriMo and if you stop writing then I don't live with my family and friends for 88 years.\"\r\n"
				+ "\"Unless I write at the end, and everyone lived happily for 88 years after. Are the pros and cons easier to weigh now?\"\r\n"
				+ "\"You know what? I accept your deal!\" then we shook hand and I walked through that door.  I saw my English classroom like it was before I left it. And then I heard Mrs. Pally call my name. So I went to the chair and the interview started. I should remind you that NaNo tv is where you pretend to be the main character from your novel and then get interviewed.\r\n"
				+ "\"Hello, guest. Welcome to NaNo tv!\" Mrs. Pally said. \"To start this interview, l will ask you your name. So what is your name?\"\r\n"
				+ "\"CREEPER_KILLER42,\" I replied. That was the name of the main character in my novel. I wonder if the leader had to do NaNo tv.\r\n"
				+ "\"What an odd name you have. What do you know about it?\"\r\n"
				+ "\"Well, I know that I chose my name. The reason why is because I am a player in Minecraft so I got to choose my name.\"\r\n"
				+ "\"What is it like to be a player in Minecraft?\"\r\n"
				+ "\"Well, I just started. It’s blocky and pixelated. It’s like a video game. I use to live in a cave but now I have a small house that I built. There aren't any shops in Minecraft so you have to get your own stuff.\"\r\n"
				+ "\"Are there other people in Minecraft? Do you live in a city?\"\r\n"
				+ "\"Well, I know that there are other players in Minecraft but I haven't found any. And I live in the wilderness.\"\r\n"
				+ "\"What is it like living in the wilderness?\"\r\n"
				+ "\"Well, it is beautiful and I have to have a farm for food. I get recourses from a mine. I have to collect wood.\"\r\n"
				+ "\"OK. Do you have a greatest fear?\"\r\n"
				+ "\"Yes. My greatest fear is that I will be outside in the night with so many monsters that I can't fight off all of them.\"\r\n"
				+ "\"So do you hide inside all night?\"\r\n"
				+ "\"Well yes. But sometimes I come back from the mine deep in the ground and I come back up and its night. And sometimes monsters chase me out of the mine.\"\r\n"
				+ "\"Well then. What is your goal in life?\"\r\n"
				+ "\"My goal in life is to slay the ender dragon and to find other players.\"\r\n"
				+ "\"And how will you achieve these goals?\"\r\n"
				+ "\"I will get the gear I need to slay the ender dragon, and I will not stop searching until I find players.\"\r\n"
				+ "\"Do we have any questions from the audience?\" the whole audience raised their hands. And what do I know? The leader is raising his hand. And the teacher calls on him first.\r\n"
				+ "He asks, \"Do you think that Minecraft is in the real world?\" In that moment, it was as if everyone in the classroom had froze except for me and the leader. I could tell he was talking to me. Not to me when I was pretending to be CREEPER_KILLER42.\r\n"
				+ "\"I...I don't know. I suppose it could be if NaNoWriMo is in the real world.\" I reply. \"Is it really in the real world?\"\r\n"
				+ "\"Actually, it is in the real world. But you are not. You are just words on a screen. I didn't even use a paper and a pencil. So you aren't even something physical. You are pretty much just electricity. 1s and 0s. That make up words on a screen. Because it’s on a screen, it doesn't exist. The words are just an allusion. You are just an allusion.\" and then he disappeared. And the classroom unfroze. But a lot of the hands went down. And then, all of them went down. And then the classroom disappeared. And I was falling from the sky.\r\n"
				+ "I was above the school. And then I fell through a hole in the school into my English classroom. There was my chrome book already booted up and on NaNo. I wasn't even hurt from the fall. The hole sealed up. And I started typing as if my life depended on it. Well, it probably did. And then I found a note. It said This is the real novel world. That other classroom you were just in was a fake. It was pretty much a simulator. Then the note ended.\r\n"
				+ "So I started typing more. I made a part where my character found diamonds. Lots of diamonds. He was able to make diamond gear. So he started looking for the books he needed to enchant it. And then, he found players in the mine. They had a farm and a wall with a door. So he went through the door. And then there were all the players. They had a great underground village. They even had a tree farm.\r\n"
				+ "\"Who are you?\" one of the players said with a hostile tone.\r\n"
				+ "\"I come in peace. I am CREEPER_KILLER42,\" he replied.\r\n"
				+ "\"Where do you come from?\"\r\n"
				+ "\"I come from the forest up above. I have been alone until now.\" so they decided to work together and create a mighty city. And then I realized, my novel was at 9,935 words!\r\n"
				+ "\"My novel is also at that.\" I heard the leader say. \"You are almost done. And I will soon write, \"And they lived happily for 88 years.\" But you still have to finish your novel. This world depends on it.\" and then, a crowd of people appeared. It was like a sporting event. I was in the center. They were all chanting my name. I was now at 9,975 words. And I looked around and it appeared on giant screens as a fraction out of 10,000. Then I was at 9,990 words. Then at 9,995. 9,996, 9,997, 9,998, 9,999. And then I stopped for a moment. What if the leader was lying? What if I get shot write now?\r\n"
				+ "But then I hear the crowd cheering, \"Write! Write! Write! Write! Write!\" so I wrote my last word. And I hear the noise it makes when you finish. It was coming from giant speakers. There were fireworks and confetti cannons! The crowd was cheering. And then a big banner came down. And it said. And they all lived happily for 88 years. And then the leader pressed a button and ended the novel.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n";
		
	}
	
}
